# Generated by Django 5.1.5 on 2025-02-03 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(error_messages={'null': 'An author is required for the post.'}, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(error_messages={'blank': 'Post content cannot be empty.', 'null': 'Post content is required.'}, validators=[django.core.validators.MinLengthValidator(10, message='Post content must be at least 10 characters long.'), django.core.validators.MaxLengthValidator(50, message='Post content cannot exceed 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already in use. Please use a different one.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken. Please choose another.'}, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be alphanumeric', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
