from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, PostViewSet, CommentViewSet

# Initialize the router
router = DefaultRouter()
router.register(r'users', UserViewSet)   # This automatically handles GET, POST, PUT, DELETE for users
router.register(r'posts', PostViewSet)   # This automatically handles GET, POST, PUT, DELETE for posts
router.register(r'comments', CommentViewSet)  # This automatically handles GET, POST, PUT, DELETE for comments

urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by the router
]
